// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZkcirAQPY0VG_S0ESxnw-GxT3sGCT-g',
    appId: '1:164064976547:web:a95a6f624f49e23e632916',
    messagingSenderId: '164064976547',
    projectId: 'flutter-login-6216b',
    authDomain: 'flutter-login-6216b.firebaseapp.com',
    storageBucket: 'flutter-login-6216b.firebasestorage.app',
    measurementId: 'G-Z4PJE00TZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEjZfkJ3GDRE6bvZZeLG9N1liZPpi5cY',
    appId: '1:164064976547:android:ab385a52daaf4a5f632916',
    messagingSenderId: '164064976547',
    projectId: 'flutter-login-6216b',
    storageBucket: 'flutter-login-6216b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD74iXApYfoFYj5K58vyj2vV2h7j3QEWeo',
    appId: '1:164064976547:ios:485d3e46887f579c632916',
    messagingSenderId: '164064976547',
    projectId: 'flutter-login-6216b',
    storageBucket: 'flutter-login-6216b.firebasestorage.app',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD74iXApYfoFYj5K58vyj2vV2h7j3QEWeo',
    appId: '1:164064976547:ios:485d3e46887f579c632916',
    messagingSenderId: '164064976547',
    projectId: 'flutter-login-6216b',
    storageBucket: 'flutter-login-6216b.firebasestorage.app',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZkcirAQPY0VG_S0ESxnw-GxT3sGCT-g',
    appId: '1:164064976547:web:8e96e5dcdebbae9a632916',
    messagingSenderId: '164064976547',
    projectId: 'flutter-login-6216b',
    authDomain: 'flutter-login-6216b.firebaseapp.com',
    storageBucket: 'flutter-login-6216b.firebasestorage.app',
    measurementId: 'G-82JYKCGEJB',
  );
}
